version: '2'

services:
  app2:
    container_name: app2
    image: 'thigk_app2'
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_ACTIVEMQ_BROKER-URL=tcp://activemq:61616
      
    
  activemq:
    image: rmohr/activemq:5.10.0
    container_name: activemq
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password    
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048
    volumes:
      - "./activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - 8161:8161
      - 61616:61616
        