version: '2'

services:
  app:
    container_name: app
    image: 'thigk_app1'
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Products
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sapassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sapassword
      - POSTGRES_DB=Products
    volumes:
      - db-data:/var/lib/postgressql/data
    ports:
      - "5432:5432"
        
volumes:
  db-data:
